title: Konrad Kasprzyk
description: Zapraszam do zapoznania się z przykładowymi projektami wykonanymi przeze mnie.
show_downloads: false
theme: jekyll-theme-architect
site.url: http://kondziuorno.github.io
